### ISSUE TITLE
When will Medformer be available?

### ISSUE THREAD

**Issue by franklinxzw** [yhygao/CBIM-Medical-Image-Segmentation#10]
Hi Yunhe,

I've read your new updated paper here: https://arxiv.org/pdf/2203.00131.pdf. Your results are very interesting and I'm interested in using your newly proposed Medformer. When will your transformer-based model Medformer be available?

**Comment by ORlGlN** [comment]
Hi Yunhe,

I came across your paper as well, is there any update regarding the code for Medformer?

Thanks!

**Comment by yhygao** [comment]
Hi all,
Sorry for the late reply. I was busy with another project this summer. Now I'm back to maintain this repo.

Our new model was first named as UTNetV2. After careful discussion, for the consideration of impact and review issues, we believe that UTNetv2 has sufficient innovation and superior performance. So we renamed UTNetV2 to MedFormer, as calling UTNetV2 makes this work seem incremental.

I'll clean up the code base and rename UTNetV2 to MedFormer in this repo.

Best,
Yunhe
