### ISSUE TITLE
Uk biobank data

### ISSUE THREAD

**Issue by alalbiol** [yhygao/CBIM-Medical-Image-Segmentation#12]
Hi, in your paper you mention the Uk biobank data. I have just registered in the Uk biobank but I can find how to download the data. Could you please tell us how to find the data, once registered in the Uk biobank?

Thanks!

**Comment by yhygao** [comment]
UK Biobank is a paid dataset. You need to submit an application and pay a fee for access to the data. I recommend you email them to ask for more details about the purchase and access to data.
