### ISSUE TITLE
About dataset_conversion file

### ISSUE THREAD

**Issue by AliMedVisionTech** [yhygao/CBIM-Medical-Image-Segmentation#22]
Would you please upload a 2D dataset_conversion file of AMOS dataset ?

**Comment by yhygao** [comment]
Hi, 

Thank you for your interest in our work. The AMOS dataset is a high-resolution 3D CT dataset. The difference with 3D models with 2D models would be large. If you want to use 2D models, you can either directly use the 3D dataset_conversion, or refer to the ACDC dataset for a 2D version of dataset_conversion. The only difference between the preprocessing of 2D and 3D is that 2D doesn't need to resample along the z-direction.

**Comment by haideralimughal** [comment]
Thanks for your kind response. According to your advice i did the dataset_conversion of acdc data into 3D dataset_conversion, and trying to run your code using the medformer model. But unfortunately getting this error.

RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: D:\a\1\sitk\Code\IO\src\sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "C:/Users/lenovo/PycharmProjects/CBIMM/dataset/acdc/acdc_3d\patient021_0.nii.gz" does not exist.

**Comment by haideralimughal** [comment]
This is my query of code for the training (python train.py --model medformer --dimension 3d --dataset acdc --batch_size 3 --unique_name acdc_3d_medformer --gpu 0) and this is the data_root: (C:/Users/lenovo/PycharmProjects/CBIMM/dataset/acdc/acdc_3d)

**Comment by AliMedVisionTech** [comment]
Thanks for your valuable reply.
