### ISSUE TITLE
可以加入推理的代码吗

### ISSUE THREAD

**Issue by ruifenggong** [yhygao/CBIM-Medical-Image-Segmentation#4]
你好，请问在训练得到最好的模型后，如何加载最好的模型，并推理出标签文件？

对一个没有label的test集来说，我想得到它的预测结果（nii.gz），有没有相关的代码可以参考？

**Comment by yhygao** [comment]
你可以先可以参考一下inference文件夹下，和training/validation.py 里面的代码。把预处理好的测试图像和加载好的模型传给inference函数就能够得到分割结果了，后面只要转换成nii.gz就好了。

**Comment by ruifenggong** [comment]
> 你可以先可以参考一下inference文件夹下，和training/validation.py 里面的代码。把预处理好的测试图像和加载好的模型传给inference函数就能够得到分割结果了，后面只要转换成nii.gz就好了。

ok，我试下，多谢提醒
