### ISSUE TITLE
3d UTNetV2模型

### ISSUE THREAD

**Issue by zenith779** [yhygao/CBIM-Medical-Image-Segmentation#7]
请问当训练大小为(128, 128, 128)时，使用3d UTNetV2模型训练，batch_size默认是多少啊，需要显存多少呢？

**Comment by yhygao** [comment]
In our experiment, we use batch_size 2. The memory consumption is about 39 GB. If you encounter OOM error, you may use the window_size (96, 96, 96).

**Comment by zenith779** [comment]
> In our experiment, we use batch_size 2. The memory consumption is about 39 GB. If you encounter OOM error, you may use the window_size (96, 96, 96).

thank you for your reply.
